rag:
  collection_name: "mental_health_docs"
  embedding_model: "all-MiniLM-L6-v2"
  embedding_dim: 384
  chunk_size: 256
  chunk_overlap: 32
  processed_docs_dir: "processed_docs"
  knowledge_dir: "knowledge"
  
  # Qdrant settings
  use_local: true
  url: "http://localhost:6333"
  distance_metric: "Cosine"
  
  # Optimized reranker settings for speed
  reranker_model: "cross-encoder/ms-marco-MiniLM-L-6-v2"
  reranker_top_k: 3  # Reduced from 5 to 3 for faster processing
  
  # Response generation
  max_context_length: 1024  # Reduced from 2048 for faster processing
  response_format_instructions: ""
  include_sources: true
  min_retrieval_confidence: 0.5  # Increased from 0.4 for better quality/speed trade-off
  top_k: 3  # Reduced from 5 for faster retrieval
  max_context_docs: 3  # Reduced for faster processing

